# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser.ui'
#
# Created: Wed Jun 17 22:41:14 2009
#      by: PyQt4 UI code generator 4.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 659)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setMargin(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layMain = QtGui.QVBoxLayout()
        self.layMain.setObjectName("layMain")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnBack = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBack.sizePolicy().hasHeightForWidth())
        self.btnBack.setSizePolicy(sizePolicy)
        self.btnBack.setMaximumSize(QtCore.QSize(34, 16777215))
        self.btnBack.setIconSize(QtCore.QSize(24, 24))
        self.btnBack.setFlat(True)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout_2.addWidget(self.btnBack)
        self.btnForward = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnForward.sizePolicy().hasHeightForWidth())
        self.btnForward.setSizePolicy(sizePolicy)
        self.btnForward.setMaximumSize(QtCore.QSize(34, 16777215))
        self.btnForward.setIconSize(QtCore.QSize(24, 24))
        self.btnForward.setFlat(True)
        self.btnForward.setObjectName("btnForward")
        self.horizontalLayout_2.addWidget(self.btnForward)
        self.btnGo = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGo.sizePolicy().hasHeightForWidth())
        self.btnGo.setSizePolicy(sizePolicy)
        self.btnGo.setMaximumSize(QtCore.QSize(34, 16777215))
        self.btnGo.setIconSize(QtCore.QSize(24, 24))
        self.btnGo.setFlat(True)
        self.btnGo.setObjectName("btnGo")
        self.horizontalLayout_2.addWidget(self.btnGo)
        self.txtAddress = MyLineEdit(self.centralwidget)
        self.txtAddress.setObjectName("txtAddress")
        self.horizontalLayout_2.addWidget(self.txtAddress)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.txtSearch = MyLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSearch.sizePolicy().hasHeightForWidth())
        self.txtSearch.setSizePolicy(sizePolicy)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout_2.addWidget(self.txtSearch)
        self.layMain.addLayout(self.horizontalLayout_2)
        self.tabWidget = MyTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wvDisplay = MyWebView(self.tab1)
        self.wvDisplay.setUrl(QtCore.QUrl("about:blank"))
        self.wvDisplay.setObjectName("wvDisplay")
        self.verticalLayout.addWidget(self.wvDisplay)
        self.tabWidget.addTab(self.tab1, "")
        self.layMain.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCloseFind = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCloseFind.sizePolicy().hasHeightForWidth())
        self.btnCloseFind.setSizePolicy(sizePolicy)
        self.btnCloseFind.setFlat(True)
        self.btnCloseFind.setObjectName("btnCloseFind")
        self.horizontalLayout.addWidget(self.btnCloseFind)
        self.lbFind = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbFind.sizePolicy().hasHeightForWidth())
        self.lbFind.setSizePolicy(sizePolicy)
        self.lbFind.setObjectName("lbFind")
        self.horizontalLayout.addWidget(self.lbFind)
        self.txtFind = MyLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtFind.sizePolicy().hasHeightForWidth())
        self.txtFind.setSizePolicy(sizePolicy)
        self.txtFind.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtFind.setDragEnabled(True)
        self.txtFind.setObjectName("txtFind")
        self.horizontalLayout.addWidget(self.txtFind)
        self.lbNotFound = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbNotFound.sizePolicy().hasHeightForWidth())
        self.lbNotFound.setSizePolicy(sizePolicy)
        self.lbNotFound.setObjectName("lbNotFound")
        self.horizontalLayout.addWidget(self.lbNotFound)
        self.lbFound = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbFound.sizePolicy().hasHeightForWidth())
        self.lbFound.setSizePolicy(sizePolicy)
        self.lbFound.setObjectName("lbFound")
        self.horizontalLayout.addWidget(self.lbFound)
        self.layMain.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.layMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 26))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menuHi_story = QtGui.QMenu(self.menubar)
        self.menuHi_story.setObjectName("menuHi_story")
        self.menu_Bookmarks = QtGui.QMenu(self.menubar)
        self.menu_Bookmarks.setObjectName("menu_Bookmarks")
        self.menu_Window = QtGui.QMenu(self.menubar)
        self.menu_Window.setObjectName("menu_Window")
        self.menu_Tool = QtGui.QMenu(self.menubar)
        self.menu_Tool.setObjectName("menu_Tool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew_Tab = QtGui.QAction(MainWindow)
        self.actionNew_Tab.setObjectName("actionNew_Tab")
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.action_Find = QtGui.QAction(MainWindow)
        self.action_Find.setCheckable(True)
        self.action_Find.setObjectName("action_Find")
        self.action_Close_Tab = QtGui.QAction(MainWindow)
        self.action_Close_Tab.setObjectName("action_Close_Tab")
        self.action_Google_Translator = QtGui.QAction(MainWindow)
        self.action_Google_Translator.setCheckable(True)
        self.action_Google_Translator.setObjectName("action_Google_Translator")
        self.action_Feed_Reader = QtGui.QAction(MainWindow)
        self.action_Feed_Reader.setCheckable(True)
        self.action_Feed_Reader.setObjectName("action_Feed_Reader")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuFile.addAction(self.actionNew_Tab)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Close_Tab)
        self.menuFile.addAction(self.actionE_xit)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionAbout)
        self.menu_Edit.addAction(self.action_Find)
        self.menu_Tool.addAction(self.action_Google_Translator)
        self.menu_Tool.addAction(self.action_Feed_Reader)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuHi_story.menuAction())
        self.menubar.addAction(self.menu_Bookmarks.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.menubar.addAction(self.menu_Tool.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Web Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBack.setToolTip(QtGui.QApplication.translate("MainWindow", "Go back one page", None, QtGui.QApplication.UnicodeUTF8))
        self.btnForward.setToolTip(QtGui.QApplication.translate("MainWindow", "Go forward one page", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGo.setToolTip(QtGui.QApplication.translate("MainWindow", "Reload current page", None, QtGui.QApplication.UnicodeUTF8))
        self.txtSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "about:blank", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCloseFind.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lbFind.setText(QtGui.QApplication.translate("MainWindow", "Find text:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbNotFound.setText(QtGui.QApplication.translate("MainWindow", "Phrase not found", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHi_story.setTitle(QtGui.QApplication.translate("MainWindow", "Hi&story", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Bookmarks.setTitle(QtGui.QApplication.translate("MainWindow", "&Bookmarks", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Window.setTitle(QtGui.QApplication.translate("MainWindow", "&Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Tool.setTitle(QtGui.QApplication.translate("MainWindow", "&Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save &As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Tab.setText(QtGui.QApplication.translate("MainWindow", "New &Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Tab.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Find.setText(QtGui.QApplication.translate("MainWindow", "&Find", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Find.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close_Tab.setText(QtGui.QApplication.translate("MainWindow", "&Close Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close_Tab.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Google_Translator.setText(QtGui.QApplication.translate("MainWindow", "&Google Translator", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Google_Translator.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+G", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Feed_Reader.setText(QtGui.QApplication.translate("MainWindow", "&Feed Reader", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Feed_Reader.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About &Qt", None, QtGui.QApplication.UnicodeUTF8))

from mytabwidget import MyTabWidget
from mylineedit import MyLineEdit
from mywebview import MyWebView
